---
title: "FLAG ribosome profiling"
output: html_notebook
---

```{r}
rm(list=ls())

### PACKAGES
library(gplots)
library(ggplot2)
library(stats)
library(grDevices)
library(dplyr)
library(readxl)
library(tidyr)
library(ggpubr)
library(limma)
library(GO.db)

### DIRECTORIES
root_dir = "/Users/adelexu/Google Drive/PhD/S27L_manuscript/source_data/analysis_plotting_code"
project_dir = file.path(root_dir, "flag_ribosome_profiling")
input_dir = file.path(project_dir, "data")
output_dir = file.path(project_dir, "results")

ip_v_tot_file = file.path(input_dir, "20220303_ip_v_tot.csv")

expr_file = file.path(input_dir, "20220303_ip_v_tot_expr.csv")

mart_entrez_file = file.path(input_dir, "mart_tid_entrez.txt")
```

```{r}
# read in input
ip_v_tot = read.csv(ip_v_tot_file)

blacklist = c('Tmod3_ENSMUST00000072232')
pal = c('black', '#D55E00', '#56B4E9')

ip_v_tot$plot_fill = factor(ip_v_tot$plot_fill, levels = pal)
```

```{r}
# plot
pdf(file = file.path(output_dir, "20220303_volcano.pdf"), height = 4, width=4)

ggplot(data=ip_v_tot[!(rownames(ip_v_tot) %in% blacklist),], aes(x=logFC, y=neglog10p, color=plot_fill)) + geom_point() + scale_color_manual(values=pal) + theme_classic() + theme(legend.position='none')

dev.off()
```

```{r}
v = read.csv(expr_file, row.names=1)
```

```{r}
goi = 'Slc6a1_ENSMUST00000032454'
norm_counts = unlist(2^v[goi,])

palette = c('#56B4E9', '#4187AF', '#E69F00', '#D55E00', 'gray50')

df = data.frame(sample = names(norm_counts), cpm = norm_counts)
df = separate(df, sample, c("lane", "clone", "fraction", "rfp"))
df$lines = factor(df$clone, 
                  levels=c('2b12', '2c3', '2c4',
                          '4a2', '4a3', '4b7',
                          '5a1', '5a2', '5a3'),
                  labels=c('S27.2b12', 'S27.2c3', 'S27.2c4',
                          'S27L.4a2', 'S27L.4a3', 'S27L.4b7',
                          'UE.5a1', 'UE.5a2', 'UE.5a3'))
df = separate(df, lines, c('line', 'clone_again'))
df$xlabels = factor(paste(df$line, df$fraction, sep=" "), levels = c('S27 tot', 'S27 ip', 'S27L tot', 'S27L ip', 'UE tot'))

pdf(file = file.path(output_dir, paste0(goi, ".pdf")), height=4, width=4)
p1 = ggplot(df, aes(x=xlabels, y=cpm)) + geom_point(aes(color = xlabels), size=2.5) + geom_path(aes(group=clone)) + ggtitle(goi) + theme_classic() + theme(legend.position = 'none', axis.text.x = element_text(angle = 90)) + expand_limits(y=0) + scale_color_manual(values = palette)
plot(p1)
dev.off()
```

```{r}
s27l_enriched = data.frame(name_ensembl = ip_v_tot[ip_v_tot$logFC > 0.25 & ip_v_tot$adj.P.Val < 0.05,"X"])
s27l_enriched = separate(s27l_enriched, name_ensembl, into=c("name", "ensembl"), remove=FALSE)

# exclude Tmod3
s27l_enriched = s27l_enriched[s27l_enriched$name != "Tmod3",]
```

```{r}
# gene ontology
mart_entrez = read.csv(mart_entrez_file, sep='\t', header=TRUE)
mart_entrez = mart_entrez[!is.na(mart_entrez$NCBI.gene.ID),]
mart_entrez = mart_entrez[!duplicated(mart_entrez$Transcript.stable.ID),]
```

```{r}
mart_entrez_s27L_enriched = mart_entrez[mart_entrez$Transcript.stable.ID %in% s27l_enriched$ensembl,]
```

```{r}
go = goana(unlist(mart_entrez_s27L_enriched$NCBI.gene.ID), species='Mm')
go = go[order(go$P.DE),]
go[go$Ont=='BP',]
```
```{r}
go_bp = go[go$Ont=='BP',]
write.csv(go_bp, file = file.path(output_dir, "s27l_enriched_46_genes_go_bp.csv"))
```



```{r}
# MA plots for total RPFs - S27L vs S27
comparison = read.csv(file.path(input_dir, "20220303_tot_s27l_vs_s27_toptable.csv"))
comparison_output_name = "tot_s27l_vs_s27"

comparison$signif = comparison$adj.P.Val < 0.05
comparison$color = rep("black", nrow(comparison))
comparison[comparison$signif,"color"] = "#CC79A7"

pdf(file = file.path(output_dir, paste0(comparison_output_name, "_ma.pdf")))

plot(x = comparison$AveExpr,
     y = comparison$logFC,
     pch = 19,
     col = comparison$color,
     ylim = c(-3, 3))

dev.off()
```

```{r}
# MA plots for total RPFs - S27L vs WT
comparison = read.csv(file.path(input_dir, "20220303_tot_s27l_vs_wt_toptable.csv"))
comparison_output_name = "tot_s27l_vs_wt"

comparison$signif = comparison$adj.P.Val < 0.05
comparison$color = rep("black", nrow(comparison))
comparison[comparison$signif,"color"] = "#CC79A7"

pdf(file = file.path(output_dir, paste0(comparison_output_name, "_ma.pdf")))

plot(x = comparison$AveExpr,
     y = comparison$logFC,
     pch = 19,
     col = comparison$color,
     ylim = c(-3, 3))

dev.off()
```

```{r}
# MA plots for total RPFs - S27 vs WT
comparison = read.csv(file.path(input_dir, "20220303_tot_s27_vs_wt_toptable.csv"))
comparison_output_name = "tot_s27_vs_wt"

comparison$signif = comparison$adj.P.Val < 0.05
comparison$color = rep("black", nrow(comparison))
comparison[comparison$signif,"color"] = "#CC79A7"

pdf(file = file.path(output_dir, paste0(comparison_output_name, "_ma.pdf")))

plot(x = comparison$AveExpr,
     y = comparison$logFC,
     pch = 19,
     col = comparison$color,
     ylim = c(-3, 3))

dev.off()
```

```{r}
# MA plots for S27 IP vs tot RPFs
comparison = read.csv(file.path(input_dir, "20220303_s27_ip_vs_tot_toptable.csv"))
comparison_output_name = "s27_ip_vs_tot"

comparison$signif = comparison$adj.P.Val < 0.05
comparison$color = rep("black", nrow(comparison))
comparison[comparison$signif,"color"] = "#CC79A7"

pdf(file = file.path(output_dir, paste0(comparison_output_name, "_ma.pdf")))

plot(x = comparison[!comparison$signif,"AveExpr"],
     y = comparison[!comparison$signif,"logFC"],
     pch = 19,
     col = "black",
     ylim = c(-3, 3))

points(x = comparison[comparison$signif,"AveExpr"],
     y = comparison[comparison$signif,"logFC"],
     pch = 19,
     col = "#CC79A7",
     ylim = c(-3, 3))

dev.off()
```

```{r}
# MA plots for S27L IP vs tot RPFs
comparison = read.csv(file.path(input_dir, "20220303_s27l_ip_vs_tot_toptable.csv"))
comparison_output_name = "s27l_ip_vs_tot"

comparison$signif = comparison$adj.P.Val < 0.05
comparison$color = rep("black", nrow(comparison))
comparison[comparison$signif,"color"] = "#CC79A7"

pdf(file = file.path(output_dir, paste0(comparison_output_name, "_ma.pdf")))

plot(x = comparison[!comparison$signif,"AveExpr"],
     y = comparison[!comparison$signif,"logFC"],
     pch = 19,
     col = "black",
     ylim = c(-3, 3))

points(x = comparison[comparison$signif,"AveExpr"],
     y = comparison[comparison$signif,"logFC"],
     pch = 19,
     col = "#CC79A7",
     ylim = c(-3, 3))

dev.off()
```
